version: "3"

services:
  database:
    container_name: database
    image: mysql:latest
    volumes:
      - "./database/database:/var/lib/mysql:rw"
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=user"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
    ports:
      - 3001:3001
    command: "mysqld --port=3001"

  web:
    container_name: web
    build: .
    depends_on:
      - database
    environment:
      - "DB_HOST=database1"
      - "DB_PORT=3001"
      - "DB_DATABASE=user"
      - "DB_USER=user"
      - "DB_PASSWORD=password"
      - "PHP_PORT=3000"
      - "PHP_HOST=0.0.0.0"
      - "DEFAULT_ADMIN_USERNAME=Administrador"
    ports:
      - 3000:3000
